---
sidebar: sidebar 
permalink: oracle/aws-ora-fsx-ec2-migration.html 
summary: 'Questa sezione fornisce dettagli sui fattori da considerare durante la migrazione del database Oracle da locale a un"istanza AWS EC2 e allo storage FSx.' 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= Migrazione del database da locale a cloud pubblico
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La migrazione del database è un'impresa impegnativa sotto ogni aspetto.  La migrazione di un database Oracle da locale al cloud non fa eccezione.

Le sezioni seguenti illustrano i fattori chiave da considerare durante la migrazione dei database Oracle al cloud pubblico AWS con la piattaforma di elaborazione AWS EC2 e di storage FSx.



== L'archiviazione ONTAP è disponibile in sede

Se il database Oracle locale si trova su un array di storage ONTAP , è più semplice impostare la replica per la migrazione del database utilizzando la tecnologia NetApp SnapMirror integrata nello storage AWS FSx ONTAP .  Il processo di migrazione può essere orchestrato utilizzando la console NetApp BlueXP .

. Creare un'istanza EC2 di calcolo di destinazione che corrisponda all'istanza locale.
. Fornire volumi di database corrispondenti e di dimensioni uguali dalla console FSx.
. Montare i volumi del database FSx sull'istanza EC2.
. Impostare la replica SnapMirror tra i volumi del database locale e i volumi del database FSx di destinazione.  La sincronizzazione iniziale potrebbe richiedere del tempo per spostare i dati di origine primari, ma gli aggiornamenti incrementali successivi saranno molto più rapidi.
. Al momento del passaggio, chiudere l'applicazione principale per interrompere tutte le transazioni.  Dall'interfaccia CLI di Oracle sqlplus, eseguire un cambio di log online di Oracle e consentire alla sincronizzazione SnapMirror di inviare l'ultimo log archiviato al volume di destinazione.
. Suddividere i volumi speculari, eseguire il ripristino Oracle sulla destinazione e avviare il database per l'assistenza.
. Indirizzare le applicazioni al database Oracle nel cloud.


Il seguente video mostra come migrare un database Oracle da locale ad AWS FSx/EC2 utilizzando la console NetApp BlueXP e la replica SnapMirror .

.Migrazione di Oracle DB on-premise su AWS
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto]


== L'archiviazione ONTAP non è disponibile in sede

Se il database Oracle locale è ospitato su un archivio di terze parti diverso da ONTAP, la migrazione del database si basa sul ripristino di una copia di backup del database Oracle.  È necessario riprodurre il registro dell'archivio per aggiornarlo prima di passare all'altro.

AWS S3 può essere utilizzato come area di archiviazione temporanea per lo spostamento e la migrazione del database.  Per questo metodo, vedere i seguenti passaggi di alto livello:

. Fornire una nuova istanza EC2 corrispondente, confrontabile con l'istanza locale.
. Fornire volumi di database uguali dall'archiviazione FSx e montare i volumi sull'istanza EC2.
. Creare una copia di backup di Oracle a livello di disco.
. Spostare la copia di backup nello storage AWS S3.
. Ricreare il file di controllo Oracle e ripristinare e recuperare il database estraendo i dati e il registro di archivio dall'archiviazione S3.
. Sincronizzare il database Oracle di destinazione con il database di origine locale.
. Al momento del passaggio, arrestare l'applicazione e il database Oracle di origine.  Copiare gli ultimi log di archivio e applicarli al database Oracle di destinazione per aggiornarlo.
. Avviare il database di destinazione per l'accesso utente.
. Reindirizzare l'applicazione al database di destinazione per completare il passaggio.




== Migrazione di database Oracle locali su AWS FSx/EC2 utilizzando la rilocazione PDB con la massima disponibilità

Questo approccio di migrazione è più adatto ai database Oracle già distribuiti nel modello multitenant PDB/CDB e in cui lo storage ONTAP non è disponibile in locale.  Il metodo di rilocazione PDB utilizza la tecnologia di clonazione a caldo Oracle PDB per spostare i PDB tra un CDB di origine e un CDB di destinazione, riducendo al minimo l'interruzione del servizio.

Per prima cosa, crea un CDB in AWS FSx/EC2 con spazio di archiviazione sufficiente per ospitare i PDB da migrare da locale.  È possibile spostare più PDB locali uno alla volta.

. Se il database locale viene distribuito in una singola istanza anziché nel modello PDB/CDB multitenant, seguire le istruzioni inlink:azure-ora-nfile-migration.html#converting-a-single-instance-non-cdb-to-a-pdb-in-a-multitenant-cdb["Conversione di una singola istanza non CDB in un PDB in un CDB multitenant"^] per convertire la singola istanza in PDB/CDB multitenant.  Quindi seguire il passaggio successivo per migrare il PDB convertito in CDB in AWS FSx/EC2.
. Se il database locale è già distribuito nel modello PDB/CDB multitenant, seguire le istruzioni inlink:azure-ora-nfile-migration.html#migrate-on-premises-oracle-databases-to-azure-with-pdb-relocation["Migrazione dei database Oracle locali sul cloud con la rilocazione PDB"^] per eseguire la migrazione.


Il seguente video mostra come un database Oracle (PDB) può essere migrato su FSx/EC2 utilizzando la rilocazione PDB con la massima disponibilità.

link:https://www.netapp.tv/insight/details/29998?playlist_id=0&mcid=85384745435828386870393606008847491796["Migrazione di Oracle PDB on-prem su AWS CDB con la massima disponibilità"^]


NOTE: Sebbene le istruzioni nei passaggi 1 e 2 siano illustrate nel contesto del cloud pubblico di Azure, le procedure sono applicabili al cloud AWS senza alcuna modifica.

Il team di NetApp Solutions Automation fornisce un toolkit di migrazione che può facilitare la migrazione del database Oracle da locale al cloud AWS.  Utilizzare il seguente comando per scaricare il toolkit di migrazione del database Oracle per la rilocazione del PDB.

[source, cli]
----
git clone https://github.com/NetApp-Automation/na_ora_aws_migration.git
----