---
sidebar: sidebar 
permalink: oracle/tr-4250.html 
keywords:  
summary:  
---
= TR-4250: SAP con Oracle su UNIX e NFS con NetApp Clustered Data ONTAP e SnapManager per SAP 3.4
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Nils Bauer, NetApp

[role="lead"]
TR-4250 affronta le sfide della progettazione di soluzioni di storage per supportare i prodotti della suite aziendale SAP utilizzando un database Oracle.  L'obiettivo principale di questo documento sono le comuni sfide di progettazione, implementazione, funzionamento e gestione delle infrastrutture di storage affrontate dai responsabili aziendali e IT che utilizzano le soluzioni SAP di ultima generazione.  Le raccomandazioni contenute nel presente documento sono generiche e non sono specifiche per un'applicazione SAP o per le dimensioni e l'ambito dell'implementazione SAP.  TR-4250 presuppone che il lettore abbia una conoscenza di base della tecnologia e del funzionamento dei prodotti NetApp e SAP.  TR-4250 è stato sviluppato sulla base dell'interazione tra il personale tecnico di NetApp, SAP, Oracle e i nostri clienti.

link:https://www.netapp.com/pdf.html?item=/media/19525-tr-4250.pdf["TR-4250: SAP con Oracle su UNIX e NFS con NetApp Clustered Data ONTAP e SnapManager per SAP 3.4"^]
