---
sidebar: sidebar 
permalink: automation/automation-ora-migration.html 
keywords: Oracle, AWS, FSx ONTAP, Database Migration, Oracle 19c, 
summary: La soluzione fornisce un toolkit di automazione basato su Ansible per la migrazione del database Oracle utilizzando la rilocazione PDB con metodologia di massima disponibilità.  La migrazione può essere qualsiasi combinazione di locale e cloud come origine o destinazione 
---
= Migrazione Oracle automatizzata
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Team di ingegneria delle soluzioni NetApp

[role="lead"]
Questa soluzione fornisce un toolkit di automazione basato su Ansible per la migrazione del database Oracle utilizzando la rilocazione PDB con metodologia di massima disponibilità.  La migrazione può avvenire in qualsiasi combinazione tra locale e cloud, sia come origine che come destinazione.



== Scopo

Questo toolkit automatizza la migrazione del database Oracle da locale al cloud AWS con storage FSx ONTAP e istanza di elaborazione EC2 come infrastruttura di destinazione.  Si presuppone che il cliente disponga già di un database Oracle locale distribuito nel modello CDB/PDB.  Il toolkit consentirà al cliente di spostare un PDB denominato da un database contenitore su un host Oracle utilizzando la procedura di spostamento Oracle PDB con un'opzione di disponibilità massima.  Ciò significa che il PDB di origine su qualsiasi array di storage locale viene spostato in un nuovo database contenitore con un'interruzione minima del servizio.  La procedura di rilocazione di Oracle sposterà i file di dati di Oracle mentre il database è online.  Successivamente, al momento del passaggio, quando tutti i file di dati vengono spostati sul cloud AWS, reindirizza le sessioni utente dai servizi locali ai servizi di database trasferiti.  La tecnologia sottolineata è la comprovata metodologia di clonazione a caldo di Oracle PDB.


NOTE: Sebbene il toolkit di migrazione sia sviluppato e convalidato sull'infrastruttura cloud AWS, si basa su soluzioni a livello di applicazione Oracle.  Pertanto, il toolkit è applicabile ad altre piattaforme cloud pubbliche, come Azure, GCP, ecc.

Questa soluzione affronta i seguenti casi d'uso:

* Creare un utente di migrazione e concedere i privilegi richiesti sul server DB di origine locale.
* Spostare un PDB da un CDB locale a un CDB di destinazione nel cloud mentre il PDB di origine è online fino al passaggio.




== Pubblico

Questa soluzione è destinata alle seguenti persone:

* Un DBA che migra i database Oracle da locali al cloud AWS.
* Un architetto di soluzioni di database interessato alla migrazione del database Oracle da locale al cloud AWS.
* Un amministratore di storage che gestisce lo storage AWS FSx ONTAP che supporta i database Oracle.
* Un proprietario di applicazioni che desidera migrare il database Oracle da locale al cloud AWS.




== Licenza

Accedendo, scaricando, installando o utilizzando il contenuto di questo repository GitHub, accetti i termini della licenza stabiliti inlink:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["File di licenza"^] .


NOTE: Esistono alcune restrizioni relative alla produzione e/o alla condivisione di lavori derivati dai contenuti di questo repository GitHub.  Prima di utilizzare il contenuto, assicurati di leggere i termini della licenza.  Se non accetti tutti i termini, non accedere, scaricare o utilizzare i contenuti di questo repository.



== Distribuzione della soluzione



=== Prerequisiti per la distribuzione

[%collapsible%open]
====
Per la distribuzione sono richiesti i seguenti prerequisiti.

....
Ansible v.2.10 and higher
ONTAP collection 21.19.1
Python 3
Python libraries:
  netapp-lib
  xmltodict
  jmespath
....
....
Source Oracle CDB with PDBs on-premises
Target Oracle CDB in AWS hosted on FSx and EC2 instance
Source and target CDB on same version and with same options installed
....
....
Network connectivity
  Ansible controller to source CDB
  Ansible controller to target CDB
  Source CDB to target CDB on Oracle listener port (typical 1521)
....
====


=== Scarica il toolkit

[%collapsible%open]
====
[source, cli]
----
git clone https://github.com/NetApp/na_ora_aws_migration.git
----
====


=== Configurazione delle variabili host

[%collapsible%open]
====
Le variabili host sono definite nella directory host_vars denominata {{ host_name }}.yml.  Per illustrare la configurazione tipica è incluso un file di variabili host di esempio host_name.yml.  Di seguito sono riportate alcune considerazioni chiave:

....
Source Oracle CDB - define host specific variables for the on-prem CDB
  ansible_host: IP address of source database server host
  source_oracle_sid: source Oracle CDB instance ID
  source_pdb_name: source PDB name to migrate to cloud
  source_file_directory: file directory of source PDB data files
  target_file_directory: file directory of migrated PDB data files
....
....
Target Oracle CDB - define host specific variables for the target CDB including some variables for on-prem CDB
  ansible_host: IP address of target database server host
  target_oracle_sid: target Oracle CDB instance ID
  target_pdb_name: target PDB name to be migrated to cloud (for max availability option, the source and target PDB name must be the same)
  source_oracle_sid: source Oracle CDB instance ID
  source_pdb_name: source PDB name to be migrated to cloud
  source_port: source Oracle CDB listener port
  source_oracle_domain: source Oracle database domain name
  source_file_directory: file directory of source PDB data files
  target_file_directory: file directory of migrated PDB data files
....
====


=== Configurazione del file host del server DB

[%collapsible%open]
====
Per impostazione predefinita, l'istanza AWS EC2 utilizza l'indirizzo IP per la denominazione host.  Se si utilizza un nome diverso nel file hosts per Ansible, impostare la risoluzione dei nomi host nel file /etc/hosts sia per il server di origine che per quello di destinazione.  Di seguito un esempio.

....
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
172.30.15.96 source_db_server
172.30.15.107 target_db_server
....
====


=== Esecuzione del playbook: eseguita in sequenza

[%collapsible%open]
====
. Installare i prerequisiti del controller Ansible.
+
[source, cli]
----
ansible-playbook -i hosts requirements.yml
----
+
[source, cli]
----
ansible-galaxy collection install -r collections/requirements.yml --force
----
. Eseguire attività di pre-migrazione sul server locale, presupponendo che l'amministratore sia un utente SSH per la connessione all'host Oracle locale con autorizzazione sudo.
+
[source, cli]
----
ansible-playbook -i hosts ora_pdb_relocate.yml -u admin -k -K -t ora_pdb_relo_onprem
----
. Eseguire la rilocazione di Oracle PDB dal CDB locale al CDB di destinazione nell'istanza AWS EC2, presupponendo ec2-user per la connessione all'istanza EC2 DB e db1.pem con coppie di chiavi ssh ec2-user.
+
[source, cli]
----
ansible-playbook -i hosts ora_pdb_relocate.yml -u ec2-user --private-key db1.pem -t ora_pdb_relo_primary
----


====


== Dove trovare ulteriori informazioni

Per saperne di più sull'automazione della soluzione NetApp , consultare il seguente sito Weblink:https://docs.netapp.com/us-en/netapp-solutions-dataops/automation/automation-introduction.html["Automazione delle soluzioni NetApp ^"^]
